WIP:

diff --git a/srd b/srd
--- a/srd
+++ b/srd
@@ -27,7 +27,7 @@ cmd_run() {
         shift 2
         ;;
       --uefi)
-        my_args="$my_args -drive file=qemu-utils/bios.bin,if=pflash,format=raw,readonly=true"
+        my_args="$my_args -drive file=resources/bios.bin,if=pflash,format=raw,readonly=true"
         shift
         ;;
       *)
@@ -41,7 +41,7 @@ cmd_run() {
   fi
 
   if [ -n "$with_tools" ]; then
-    my_args="$my_args -drive file=fat:rw:./tools,if=ide,format=raw"
+    my_args="$my_args -drive file=fat:rw:./tools,if=ide,index=4,format=raw"
   fi
 
   my_args="$my_args $@"
@@ -81,21 +81,50 @@ cmd_run_arm64() {
 
 cmd_install() {
   local target=$1
+  local seed="resources/gptdisk-64-sectors.raw"
 
   if [ -z "$target" ]; then
     echo "Missing target"
     exit 1
   fi
 
+  read -p "I PROMISE FIRST PARTITION STARTS AT 64 SECTORS. Press enter to continue"
+
+  local backup_file="BACKUP_$(date +%Y%m%d%H%M%S).bak"
+  echo "Backing up $target to $backup_file..."
+  dd if=$target of="$backup_file" bs=512 count=64
+
+  read -p "Begin installation?"
   echo "Installing to $target..."
-  echo "Running ./tools/bootlace.com --gpt $target"
-  ./tools/bootlace.com --gpt "$target"
+  # copy first 440 bytes of first sector
+  dd if=$seed of=$target bs=440 count=1 conv=notrunc
+  # copy from sector 34 to 63
+  dd if=$seed of=$target bs=512 count=31 skip=33 seek=33 conv=notrunc
+  echo "Done"
+}
+
+cmd_create() {
+  local target=$1
+
+  if [ -z "$target" ]; then
+    echo "Missing target"
+    exit 1
+  fi
+
+  echo "Creating $target..."
+  if [ "$(uname -s)" == "Darwin" ]; then
+    hdiutil create -size 200m -layout GPTSPUD -align 32 -fs FAT32 -volname "EFI" $target
+  else
+    echo "Unsupported OS"
+    exit 1
+  fi
 }
 
 print_usage() {
   echo "Usage:"
   echo "  $0 run [--target <target> | --uefi | --no-tools] [...args]"
   echo "  $0 run-arm64 [...args]"
+  echo "  $0 create [...args]"
   echo "  $0 install <target>"
 }
 
@@ -121,6 +150,9 @@ case "$CMD" in
     ;;
   install)
     cmd_install $@
+    ;;
+  create)
+    cmd_create $@
     ;;
   help | "")
     print_usage
